%-------------------------------%
%    Challenge Session No. 4
%-------------------------------%
%Rodrigo Gamboa & Francisco Montes | May 2024


%%%%%%%%%%%%%%%%%%%%%%%%%%
%IMPORTANT FINAL COMMENTS%
%%%%%%%%%%%%%%%%%%%%%%%%%%

% This is your minimum SECOND (and final) DELIVERABLE. The maximum (which will warranty a 
% direct 100 grade in the deliverable), and a VERY well-received thing to have for your  
% ORAL EXAM, is the integration of this code to the previous one (i.e., the one for the 
% first deliverable). In fewer words, an animation of a magnet falling through the axis  
% of a coil, experiencing magnetic braking due to the induced current by
% by the falling magnet.


%%%%%%%%%%%%%%%%
%TODAY´s SESSION
%%%%%%%%%%%%%%%%

%The objective for this session is to model/find the induced voltage 
%(potential difference, or electromotive force, namely fem), generated by 
%a magnet free falling from a zo height, along the axis of a conductor
%ring or loop (with radious Rring). IMPORTANT: The loop conductor located at 
%z=0 no longer has a steady electric current, as before. The associated 
%current will be generated by the associated induced fem.

%Assume a magnet with a magnetic dipole moment "mag".
%Assume the magnet has a small radius, 10 times smaller than the ring.
%Model the magnet as an electrical current ring of r=Rring/10
%Calculate the z component of the magnetic field produced by that ring. 


%START% PART I

%clear             %Add comment, what are these for?
%clc               %Add comment
%clf               %Add comment

           %Define a "mag" variable to define the magnetic moment
           %of the falling magnet, and set it equal to 500.

           %Define a "Rring" variable to define the ring
           %radius in m. Set it equal to 0.5.


           %Define initial position of magnet (zo). Set it equal to 0.1.
           %Define ring position (use "zring" variable). Set it equal to 0.
           %Define time step ("dt"). Set it to 0.01.
           %Define a time vector, and initialize to zero its first
           %entry.

       %Define a Z-position vector (zm), and initialize to "zo" its first
       %entry.

       %Define a "cc" counter; set it equal to 1.
       %Define a vz vector; initialize its first entry to zero.

       %Call for figure(1).
