%-------------------------------%
%    Challenge Session No. 4
%-------------------------------%
%Rodrigo Gamboa & Francisco Montes | May 2024


%%%%%%%%%%%%%%%%%%%%%%%%%%
%IMPORTANT FINAL COMMENTS%
%%%%%%%%%%%%%%%%%%%%%%%%%%

% This is your minimum SECOND (and final) DELIVERABLE. The maximum (which will warranty a 
% direct 100 grade in the deliverable), and a VERY well-received thing to have for your  
% ORAL EXAM, is the integration of this code to the previous one (i.e., the one for the 
% first deliverable). In fewer words, an animation of a magnet falling through the axis  
% of a coil, experiencing magnetic braking due to the induced current by
% by the falling magnet.


%%%%%%%%%%%%%%%%
%TODAY´s SESSION
%%%%%%%%%%%%%%%%

%The objective for this session is to model/find the induced voltage 
%(potential difference, or electromotive force, namely fem), generated by 
%a magnet free falling from a zo height, along the axis of a conductor
%ring or loop (with radious Rring). IMPORTANT: The loop conductor located at 
%z=0 no longer has a steady electric current, as before. The associated 
%current will be generated by the associated induced fem.

%Assume a magnet with a magnetic dipole moment "mag".
%Assume the magnet has a small radius, 10 times smaller than the ring.
%Model the magnet as an electrical current ring of r=Rring/10
%Calculate the z component of the magnetic field produced by that ring. 


%START% PART I

clear             % Limpia todas las variables del espacio de trabajo.
clc               %% Limpia la ventana de comandos.
clf               % Limpia las figuras abiertas (ventanas gráficas).

mag = 500;        % Se define la variable "mag" para representar el momento magnético 
                  % del imán que está cayendo.

Rring = 0.5;      % Se define el radio del anillo conductor ("Rring") en metros. 
                  % Se le asigna un valor de 0.5 m.

zo = 0.1;            % Se define la altura inicial desde la que cae el imán (zo). 
zring = 0;           % Se define la posición del anillo (en z=0).
dt = 0.01;           % Se define el paso de tiempo para la simulación como 0.01 s

t = zeros(1, 2000);  % Se crea un vector de tiempo con 2000 posiciones, inicializado en cero.
zm = zeros(1, 2000);       % Vector que almacenará las posiciones del imán en z. 
zm(1) = zo;                % Se asigna la posición inicial del imán en el primer valor del vector.
cc = 1;                    % Se define un contador "cc" que llevará el número de iteraciones.
vz = zeros(1, 2000);       % Se crea el vector de velocidades del imán (en z), iniciado en cero.


figure(1);                 % Se abre una ventana gráfica para las visualizaciones.

%--------Part 2---------% [after %Call for figure(1).]

%Use [open and close] a while loop, using the zm variable vector, such that
%you can warranty that all z values for the magnet while falling from zo to
%JUST BEFORE passing through the coil are covered (i.e., from zm = zo to 
%zm = 0.0162).


%Inside the while loop, use the following (uncomment), and
%explain what it does or will do.

%while zm(cc) > -0.2% Al usar disp([cc, t(cc), zm(cc)]) zm despliega un
% valor que ya esta cerca del limite por eso ya no avanza, le puse el nuev
% valor -0.1 para que si avanzara

while zm(cc) > 0.0172 % hace la curva, El ciclo se ejecuta mientras el imán no haya caído más allá de 0.0172
% while zm(cc) > -0.2 % Al dejar caer el imán más allá del centro (z = 0), el flujo cambia de dirección,
                      % y según la Ley de Lenz, la fem inducida se invierte bruscamente → aparece un pico.



    pause(0.001)     % Pausa la simulación brevemente para que se vea la animación.
    clf              % Limpia la figura actual para actualizarla en cada iteración.
    

    [x,y,phiB1,Bz]=B_due_M(zm(cc),mag,Rring);  

    %What is this? Explain in full detail, take your time!
    % The function B_due_M receives as input the current vertical position of the magnet (zm(cc)), 
    % the magnetic moment of the magnet (mag), and the radius of the coil (Rring). 
    % It output x and y (coordinates),
    % phiB1 the magnetic flux through the ring, 
    % and Bz is the z-component of the magnetic field at the center of the coil. 
    % In simple terms, this function calculates how strong the magnetic field is
    % and how much of it passes through the coil at the current position of the magnet. 

    %Using kinematics, the same as in last week's code actually, write an
    %expression for the zm position of the magnet, while free falling.

    % Se usa cinemática para calcular la siguiente posición del imán
    % mientras cae libremente, usando la fórmula: z = z0 + v0*dt - (1/2)*g*dt^2
    % ecuación de cinemática
    zm(cc+1) = zm(cc) + vz(cc)*dt - 0.5*9.81*dt^2;

%Using kinematics, the same as in last week's code actually, write an
%expression for the vz position of the magnet, while free falling.


    vz(cc+1) = vz(cc) - 9.81*dt;     % Se actualiza la velocidad con v = v0 - g*dt

    [x, y, phiB2, Bz] = B_due_M(zm(cc+1), mag, Rring);      % Se vuelve a llamar a la función B_due_M con la nueva posición
                                                            % para obtener el nuevo flujo magnético (phiB2) y campo Bz actualizado.

    
    %Taking into account that the B_due_M function has been called 
    %twice (why)? Calculate a vector function of fem(cc) equal to the
    %"rate change or difference of the magnetic flux, with respect to
    % time", associated with the area of the ring (coil or wire loop).

    fem(cc) = - (phiB2 - phiB1) / dt;       % Se calcula la fem como la derivada del flujo con respecto al tiempo

    %Uncomment all of the following, and explain in detals what each line 
    %is doing.

    subplot(2,2,1)
    hold on
    grid on
    xlabel 'time, s'
    ylabel 'fem, mV'
    % Se grafica la fem inducida (amplificada por 100 para convertirla a mV)
    plot(t(1:cc),100*fem(1:cc),'-k','LineWidth',1)
    plot(t(1:cc),100*fem(1:cc),'*r','LineWidth',2)
    

    subplot(2,2,2)
    hold on
    axis([0 0.3 -10 10])
    grid on
    xlabel 'time, s'
    ylabel 'magnet heigth, cm'
   % Se grafica la posición del imán en función del tiempo (convertido a cm)
    plot(t(1:cc),100*zm(1:cc),'ob','LineWidth',2)    

    subplot(2,2,3)
    hold on
    % Mapa de colores del campo magnético en plano xy (con transformación para mejor visualización)
    pcolor(x,y,zm(cc)/abs(zm(cc))*abs(abs(0.005^2*Bz)).^(1/3)); shading interp; colormap hot; colorbar
    view(-45,-45)

    subplot(2,2,4)
    
    hold on
    mesh(x,y,zm(cc)/abs(zm(cc))*abs(abs(10^2*Bz)).^(1/3)); 
    view(-30,-3)
    axis([-Rring Rring -Rring Rring -5 15])
    
    cc=cc+1;
    t(cc)=t(cc-1)+dt;
end   
% close the while loop

%END OF CODE !!!%



    %What is this? Explain in full detail, take your time!
    % Calculate the magnetic field and magnetic flux at the new position of the magnet, after it has moved. 
    % It takes the updated position zm(cc+1), the magnetic moment mag, and the coil radius Rring as inputs.
    % The function returns the values for the coordinates (x and y), the new magnetic flux through the ring (phiB2),
    % and the magnetic field along the axis (Bz). This allows us to see how the magnetic effect changes as the magnet continues to fall.

   
 % close the while loop

% Explicación adicional sobre B_due_M (segunda llamada):
% Esta función se llama dos veces en cada iteración:
% 1. Para calcular el flujo magnético actual (phiB1)
% 2. Para calcular el nuevo flujo después del movimiento del imán (phiB2)
% Así se puede aplicar la ley de Faraday para calcular la fem inducida.