%-------------------------------%
%    Challenge Session No. 4
%-------------------------------%
%Rodrigo Gamboa & Francisco Montes | May 2024


%%%%%%%%%%%%%%%%%%%%%%%%%%
%IMPORTANT FINAL COMMENTS%
%%%%%%%%%%%%%%%%%%%%%%%%%%

% This is your minimum SECOND (and final) DELIVERABLE. The maximum (which will warranty a 
% direct 100 grade in the deliverable), and a VERY well-received thing to have for your  
% ORAL EXAM, is the integration of this code to the previous one (i.e., the one for the 
% first deliverable). In fewer words, an animation of a magnet falling through the axis  
% of a coil, experiencing magnetic braking due to the induced current by
% by the falling magnet.


%%%%%%%%%%%%%%%%
%TODAY´s SESSION
%%%%%%%%%%%%%%%%

%The objective for this session is to model/find the induced voltage 
%(potential difference, or electromotive force, namely fem), generated by 
%a magnet free falling from a zo height, along the axis of a conductor
%ring or loop (with radious Rring). IMPORTANT: The loop conductor located at 
%z=0 no longer has a steady electric current, as before. The associated 
%current will be generated by the associated induced fem.

%Assume a magnet with a magnetic dipole moment "mag".
%Assume the magnet has a small radius, 10 times smaller than the ring.
%Model the magnet as an electrical current ring of r=Rring/10
%Calculate the z component of the magnetic field produced by that ring. 


%START% PART I

clear             %Add comment, what are these for?
clc               %Add comment
clf               %Add comment

mag = 500;           %Define a "mag" variable to define the magnetic moment
           %of the falling magnet, and set it equal to 500.

Rring = 0.5;           %Define a "Rring" variable to define the ring
           %radius in m. Set it equal to 0.5.


zo = 0.1;           %Define initial position of magnet (zo). Set it equal to 0.1.
zring = 0;           %Define ring position (use "zring" variable). Set it equal to 0.
dt = 0.01;           %Define time step ("dt"). Set it to 0.01.
t = zeros(1, 2000);  %Define a time vector, and initialize to zero its first
%t(1) = 0;                    %entry.

zm = zeros(1, 2000);       %Define a Z-position vector (zm), and initialize to "zo" its first
                            %entry.
zm(1) = zo;


cc = 1;       %Define a "cc" counter; set it equal to 1.
vz = zeros(1, 2000);            %Define a vz vector; initialize its first entry to zero.


figure(1);       %Call for figure(1).

%--------Part 2---------% [after %Call for figure(1).]

%Use [open and close] a while loop, using the zm variable vector, such that
%you can warranty that all z values for the magnet while falling from zo to
%JUST BEFORE passing through the coil are covered (i.e., from zm = zo to 
%zm = 0.0162).


%Inside the while loop, use the following (uncomment), and
%explain what it does or will do.

while zm(cc) > -0.1% Al usar disp([cc, t(cc), zm(cc)]) zm despliega un
% valor que ya esta cerca del limite por eso ya no avanza, le puse el nuev
% valor -0.1 para que si avanzara

%while zm(cc) > 0.0162

    pause(0.001)     %Comment
    clf              %Comment
    

    [x,y,phiB1,Bz]=B_due_M(zm(cc),mag,Rring);  

    %What is this? Explain in full detail, take your time!
    % The function B_due_M receives as input the current vertical position of the magnet (zm(cc)), 
    % the magnetic moment of the magnet (mag), and the radius of the coil (Rring). 
    % It output x and y (coordinates),
    % phiB1 the magnetic flux through the ring, 
    % and Bz is the z-component of the magnetic field at the center of the coil. 
    % In simple terms, this function calculates how strong the magnetic field is
    % and how much of it passes through the coil at the current position of the magnet. 

    %Using kinematics, the same as in last week's code actually, write an
    %expression for the zm position of the magnet, while free falling.

    zm(cc+1) = zm(cc) + vz(cc)*dt - 0.5*9.81*dt^2;

%Using kinematics, the same as in last week's code actually, write an
%expression for the vz position of the magnet, while free falling.

    vz(cc+1) = vz(cc) - 9.81*dt;

    [x, y, phiB2, Bz] = B_due_M(zm(cc+1), mag, Rring);
    
    %Taking into account that the B_due_M function has been called 
    %twice (why)? Calculate a vector function of fem(cc) equal to the
    %"rate change or difference of the magnetic flux, with respect to
    % time", associated with the area of the ring (coil or wire loop).

    fem(cc) = - (phiB2 - phiB1) / dt;

    %Uncomment all of the following, and explain in detals what each line 
    %is doing.

    subplot(2,2,1)
    hold on
    grid on
    xlabel 'time, s'
    ylabel 'fem, mV'
    plot(t(1:cc),100*fem(1:cc),'-k','LineWidth',1)
    plot(t(1:cc),100*fem(1:cc),'*r','LineWidth',2)
    

    subplot(2,2,2)
    hold on
    % AQUI EL AXIS ES 0.3 O 0.2?
    axis([0 0.3 -10 10])
    grid on
    xlabel 'time, s'
    ylabel 'magnet heigth, cm'
    plot(t(1:cc),100*zm(1:cc),'ob','LineWidth',2)    

    subplot(2,2,3)
    hold on
    pcolor(x,y,zm(cc)/abs(zm(cc))*abs(abs(0.005^2*Bz)).^(1/3)); shading interp; colormap hot; colorbar
    view(-45,-45)

    subplot(2,2,4)
    
    hold on
    mesh(x,y,zm(cc)/abs(zm(cc))*abs(abs(10^2*Bz)).^(1/3)); 
    view(-30,-3)
    axis([-Rring Rring -Rring Rring -5 15])
    
    cc=cc+1;
    t(cc)=t(cc-1)+dt;
end   
% close the while loop

%END OF CODE !!!%



    %What is this? Explain in full detail, take your time!
    % Calculate the magnetic field and magnetic flux at the new position of the magnet, after it has moved. 
    % It takes the updated position zm(cc+1), the magnetic moment mag, and the coil radius Rring as inputs.
    % The function returns the values for the coordinates (x and y), the new magnetic flux through the ring (phiB2),
    % and the magnetic field along the axis (Bz). This allows us to see how the magnetic effect changes as the magnet continues to fall.

   
 % close the while loop
